### ISSUE TITLE
Update README for developers

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/rest-api-console2#17]
I tried using the README to set up a dev environment, but it didn't work, and since I see things like a `gulpfile`, I think maybe there's undocumented steps I need to take. (I also tried running `gulp`, but it complained about a missing `config.json` file).

**Comment by codebykat** [comment]
Should be fixed now as we've just revisited setup https://github.com/Automattic/rest-api-console2/pull/19

The README now says to copy config.sample.json to config.json so that should help :)
