### ISSUE TITLE
Add support for versioned endpoints

### ISSUE THREAD

**Issue by aduth** [Automattic/rest-api-console2#3]
This is starting to look quite nice! Are versioned endpoints on your radar? Both the current API console and this newer iteration assume a base version of "v1" for paths. In the current API console, I can start my path with ".1/" to trick it into using a "/v1.1/" endpoint. This isn't very user-friendly, and neither there nor here are the latest version of endpoints used in the endpoint listing.

This will become especially relevant soon as there's [discussion of bumping all endpoints](https://operationapi.wordpress.com/2014/11/10/bumping-the-default-api-version-to-1-1/).

**Comment by beaucollins** [comment]
Versions can be switched via the version dropdown. It uses the `/v1.1/versions` endpoint to populate the menu and select the default version.
