### ISSUE TITLE
Make response variable readily available in browser JS Console

### ISSUE THREAD

**Issue by folletto** [Automattic/rest-api-console2#7]
To test ideas or do quick snippets of code would be nice to have the result of the call done in the REST Console readily available in the browser JS Console too.

I'm thinking something similar to this:

1. I do a query
2. The response triggers a console.log in the JS Console
3. The message says something like: _"Returned object available with the name `ret`."_ (always the same variable, the text work just as a reminder of the variable name, but can also use different variables for each query, incrementally `ret1`, `ret2`, etc).
4. From that moment on I can use and manipulate `ret` in the JS console

**Comment by beaucollins** [comment]
Should be simple enough.

I can also provide a function in the console so you can send requests via the browser's console and see it get logged along with the others.

**Comment by folletto** [comment]
Ohhh that would be nice :D

**Comment by beaucollins** [comment]
It looks like logging is already supported.

In the console:
```
send({ path: '/me' })
```

And it will show up in the request log.

**Comment by folletto** [comment]
Wohoo! :D
